import markdown
from fpdf import FPDF
import sys

def convert_md_to_pdf(md_file, pdf_file):
    # Read markdown
    with open(md_file, 'r', encoding='utf-8') as f:
        md_text = f.read()

    # Convert to HTML
    html = markdown.markdown(md_text, extensions=['tables'])

    # Create PDF
    class MyFPDF(FPDF):
        def header(self):
            self.set_font("helvetica", "B", 10)
            self.cell(0, 10, "Documentacao Oficial - RDL xApp", align="R")
            self.ln(10)
            
        def footer(self):
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.cell(0, 10, f"Pagina {self.page_no()}", align="C")

    pdf = MyFPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # fpdf2 write_html supports basic HTML generated by markdown
    try:
        pdf.write_html(html)
        pdf.output(pdf_file)
        print(f"PDF successfully generated: {pdf_file}")
    except Exception as e:
        print(f"Error rendering PDF: {e}")
        sys.exit(1)

if __name__ == "__main__":
    convert_md_to_pdf("docs/Manual_RDL_Consolidado.md", "docs/Manual_RDL_Consolidado.pdf")
